name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        meteorRelease:
          - '--release 1.9'
          - '--release 1.10.2'
          - '--release 1.11'
          - '--release 1.12.1'
          - '--release 2.1.1'
          - '--release 2.2'
          - '--release 2.2.1'
          - '--release 2.2.2'
          - '--release 2.2.3'
          - '--release 2.3'
          - '--release 2.3.1'
          - '--release 2.3.2'
          - '--release 2.3.3'
          - '--release 2.3.4'
          - '--release 2.3.5'
          # Latest version
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: |
          curl https://install.meteor.com | /bin/sh
          npm i -g @zodern/mtest

      - name: Run Tests
        run: |
          # Retry tests since some of them are flaky
          mtest --package ./ --once ${{ matrix.meteorRelease }} || mtest --package ./ --once ${{ matrix.meteorRelease }} 
