name: Test suite

# in this configuration the ci runs only when code is pushed to master branch or a pull request is created
# in general it is advised to not push to master directly but to create a pull request instead
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lintcode:
    name: Javascript lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-
      - run: cd test-proxy && npm ci
      - run: cd test-proxy && npm run lint:code && npm run format:code

  # at the moment we only test against meteor 3.2.2
  # because mtest is not working properly with meteor 3+
  tests:
    name: Meteor ${{ matrix.meteor }} tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup meteor
        uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '3.2.2'

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-22-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-22-
      - run: cd testapp && npm run ci
